/** Plain-language definitions for beginners (§43). */
export const GLOSSARY: { term: string; definition: string; example?: string }[] = [
  { term: "ASIN", definition: "Amazon Standard Identification Number: the 10-character ID Amazon gives each product listing.", example: "B0XXXXXXXX. Every seller of the identical product shares the same ASIN." },
  { term: "SKU", definition: "Stock Keeping Unit: your own ID for an item in your inventory. Different sellers use different SKUs for the same ASIN.", example: "SPAT-SET-001" },
  { term: "UPC / EAN / GTIN", definition: "Barcode numbers that identify a specific product version. The last digit is a check digit, so a mistyped number usually fails validation." },
  { term: "FBA", definition: "Fulfilled by Amazon: you send inventory to Amazon warehouses, and Amazon stores, ships, and handles returns for a fee." },
  { term: "FBM", definition: "Fulfilled by Merchant: you store, pack, and ship each order yourself." },
  { term: "Buy Box", definition: "The Add to Cart button on a listing. When several sellers offer the same product, Amazon decides which offer gets it. It's never guaranteed." },
  { term: "Referral fee", definition: "Amazon's commission on each sale: a percentage of the sale price that varies by category, usually with a minimum per item.", example: "15% of a $20 sale = $3.00" },
  { term: "FBA fee", definition: "The per-unit fulfillment fee for FBA orders, based on the product's size tier and shipping weight. Storage is charged separately." },
  { term: "ROI", definition: "Return on investment: profit divided by what you paid upfront, as a percentage.", example: "$9 profit ÷ $13 invested × 100 = 69.2%" },
  { term: "Margin", definition: "Profit as a percentage of the selling price.", example: "$9 profit ÷ $30 price × 100 = 30%" },
  { term: "COGS", definition: "Cost of goods sold: what the units you actually sold cost you (purchase price plus shipping and prep). Unsold inventory isn't COGS yet." },
  { term: "MOQ", definition: "Minimum order quantity: the smallest order a supplier accepts." },
  { term: "Ungating", definition: "Getting Amazon's approval to sell in a restricted category or brand. Don't assume you're approved; check in Seller Central." },
  { term: "Restricted product", definition: "A product, brand, or category that needs Amazon's approval, extra documentation, or can't be sold at all." },
  { term: "Prep", definition: "Getting items ready for FBA: labeling, bagging, bubble wrap, bundling. You can do it yourself or pay for it." },
  { term: "Repricing", definition: "Adjusting your price as competitors and demand change, manually or with a tool. Price wars can wipe out margins." },
  { term: "Sales rank (BSR)", definition: "Amazon's ranking of how well an item sells in its category, relative to other items. It's an indicator, not an exact unit count." },
  { term: "Inventory turnover", definition: "How many times you sell through your average inventory in a period: COGS ÷ average inventory. Higher means stock sells faster." },
  { term: "Cash flow", definition: "Money actually moving in and out. It differs from profit: buying inventory lowers cash now, but it only becomes a cost when the item sells." },
  { term: "Break-even price", definition: "The selling price at which you make $0 profit after all costs." },
  { term: "Maximum buy price", definition: "The most you can pay for a unit and still hit both your target profit and your target ROI." },
  { term: "Reorder point", definition: "The stock level at which to reorder: average daily sales × supplier lead time + safety stock.", example: "3/day × 10 days + 10 = 40 units" },
  { term: "Landed cost", definition: "The full cost of getting a unit ready to sell: purchase price plus shipping, prep, and other upfront costs." },
];
